### ISSUE TITLE
Add phishing / scam detection.

### ISSUE THREAD

**Issue by ThatRedox** [chunky-dev/discord-bot#7]
List of bad sites: https://github.com/nikolaischunk/discord-phishing-links

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by leMaik** [comment]
tbh i never saw a sentence with buy, transfer, western union and a link that was _not_ spam. Maybe we could score words?

**Comment by NotStirred** [comment]
also anyone sending a link with `free` `nitro`, with the account having no other messages and joined within a month
